### ISSUE TITLE
Rule out port to monochrome Game Boy

### ISSUE THREAD

**Issue by pinobatch** [AntonioND/ucity#1] opened 2017-09-01 15:15 UTC
The Super Game Boy accessory (SGB) for Super NES runs only monochrome software, as its method of colorization operates on 8x8 pixel areas of the screen, not individual background tiles or sprites. SGB users would hit this in `main.asm`:

    LONG_CALL   RoomOnlyForGBC

For the benefit of SGB users, I request some documentation of which Game Boy Color features are essential to this program. Is it the colorization? The CPU speed? The RAM? The CHR HDMA? If the workaround for SGB users is to purchase a used copy of *SimCity* (SNS-SC), I want that to be clear up front.

**Comment by AntonioND** [comment] 2017-09-01 15:31
Well, the problem is mostly the RAM. I use basically all of the VRAM for the graphics (the GBC has two banks, the GB only one) and most of the WRAM (the GBC has 32 KB, the GB only 8 KB). So that you get an idea of how impossible it is to port this to GB, I use 30 KB of WRAM.

The only way to make this fit in a GB would be to reduce a lot the number of buildings and the size of the map, and maybe remove features such as the transportation simulation so that the simulation steps aren't too slow in big cities (the CPU in GBC can run twice as fast as in the GB).

**Comment by AntonioND** [comment] 2017-09-01 15:49
I've added a note to the readme so I'm going to close this issue: https://github.com/AntonioND/ucity/commit/78f0ca0dc24f53c4027fb2b80483d1ad13d44ee1

**Closed as completed by AntonioND** 2017-09-01 15:49 UTC
